name: Build CoMetaR Docker Image

on:
  push:
    tags:
      - v[0-9]+.[0-9]+**

env:
  REGISTRY: ghcr.io
  OWNER_APPLICATION_NAME: ${{ github.repository }}

jobs:
  browser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}-${{ github.job }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}-${{ github.job }}:${{ steps.prep.outputs.version }}
          push: true
  fuseki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}-${{ github.job }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}-${{ github.job }}:${{ steps.prep.outputs.version }}
          push: true
  rest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Version
        id: prep
        run: |
          echo ::set-output name=repository::$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          echo ::set-output name=version::${GITHUB_REF#refs/tags/v}
      - name: Build and push docker image for ${{ github.job }}
        uses: docker/build-push-action@v2
        with:
          context: ./${{ github.job }}
          file: ./${{ github.job }}/Dockerfile
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}-${{ github.job }}:latest
            ${{ env.REGISTRY }}/${{ env.OWNER_APPLICATION_NAME }}-${{ github.job }}:${{ steps.prep.outputs.version }}
          push: true
